### ISSUE TITLE
Automatic Proxy config file (pac) issue for iOS devices

### ISSUE THREAD

**Issue by gta2000** [nneonneo/iOS-SOCKS-Server#24]
Hi nneonneo,

Thank you so much for sharing this useful socks server, I can get it up and run with Pythonista no problem 👍 

One issue I noticed is, after the server phone setup and I used other iOS devices (other iPhones) with automatic PAC config, the server end prints out the following exception no matter with `wpad.dat` or `wpad.pac`:
```
192.168.8.2 - - [02/Jan/2024 22:11:27] code 400, message Bad request version ('w´÷\x00*\x9a\x9a\x13\x01\x13\x02\x13\x03À,À+Ì©À0À/Ì¨À')
----------------------------------------
Exception occurred during processing of request from ('192.168.8.2', 59084)
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 293, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socketserver.py", line 748, in init
    self.handle()
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 404, in handle_one_request
    if not self.parse_request():
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 306, in parse_request
    self.send_error(
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 457, in send_error
    self.send_response(code, message)
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 491, in send_response
    self.log_request(code)
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 543, in log_request
    self.log_message('"%s" %s %s',
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/server.py", line 577, in log_message
    sys.stderr.write("%s - - [%s] %s\n" %
  File "/var/containers/Bundle/Application/313AD80F-5D09-40D2-A230-C53087831B77/Pythonista3.app/Frameworks/Py3Kit.framework/pykit_startup.py", line 12, in write
    self.write_stream(s)
ValueError: embedded null character
----------------------------------------
```
I did try access the PAC url with browser or other Android device, no such issue at all.
To me, the iOS seems sending special request to PAC server and makes it becomes 400.
The server iPhone is running the latest iOS 17.2.1 and Pythonista is on v3.4 (340012) and two client iPhones with one iOS 17.2.1 and one iOS 15.8.

**Comment by nneonneo** [comment]
It looks like the iOS device is trying to speak HTTPS (TLS) with the wpad server, which is not supported; HTTPS is a binary protocol so it confuses the HTTP parser.

Does the server still work? Try making sure the URL specified is http:// not https://.

**Comment by gta2000** [comment]
> It looks like the iOS device is trying to speak HTTPS (TLS) with the wpad server, which is not supported; HTTPS is a binary protocol so it confuses the HTTP parser.
> 
> Does the server still work? Try making sure the URL specified is http:// not https://.

Yes, I'm sure it's `http`, not `https`. 
I see the [support doc](https://support.apple.com/guide/deployment/network-proxy-configuration-settings-depb27492e34/web) from apple where it gives the example in description with `https` only, but not clearly saying it supports `http` or not on `Automatic Proxy Configuration`:
```
Setting
Enable Automatic Proxy Configuration

Description
Enable Automatic Proxy Configuration if you’re using a proxy auto-config (PAC) file. Enter the address of the PAC file in the URL field. For example, https://www.betterbag.com/filename.pac.
```

**Comment by nneonneo** [comment]
Alright, I just checked and: it looks like iOS devices start by making an HTTPS request to the PAC URL (even if `http://` is specified!), and when that fails they fall back to making an HTTP request. So, the error is harmless, even though it's irritatingly noisy. We essentially end up with two loud messages: the first is a log message complaining about the malformed input, and the second is an HTTP handler crash because Pythonista apparently refuses to write null bytes to the console. I may consider a method to silence such errors in the future, although it may require some re-engineering of the web server.

**Comment by gta2000** [comment]
> Alright, I just checked and: it looks like iOS devices start by making an HTTPS request to the PAC URL (even if `http://` is specified!), and when that fails they fall back to making an HTTP request which should go through fine. So, the error is harmless, even though it's irritatingly noisy. We essentially end up with two loud messages: the first is a log message complaining about the malformed input, and the second is an HTTP handler crash because Pythonista apparently refuses to write null bytes to the console. I may consider a method to silence such errors in the future, although it may require some re-engineering of the web server.

Thanks for the findings, so what you are saying is, the iOS devices should still receive the PAC config via the fall back `HTTP` request. But just FYI that the iOS devices I have still cannot be proxied correctly via PAC config, but it works if I do manual `http` proxy, I'll live with this for now, and again, thanks for your great contribution on this 💯

**Comment by nneonneo** [comment]
That's what seems to happen for me. I checked with a client running iOS 16.6.1 and server running iOS 17.2.1. The server spewed some error messages as expected, but the client was ultimately able to connect (verified by looking at the statistics and the client's apparent public IP address).

Ah well, at least you got it working! Thanks for the report - I'll keep an eye out to see if I can repro this someday and pin down the cause.

**Comment by gta2000** [comment]
One last thing I wanna mentioned is, I ran this with a mobile Wi-Fi device which has NO internet access at all, so it purely works as a  local area network router and forces every bit of data going through the SOCKS iPhone Server, I don't know if there would be any difference compare a router has internet access 🤔
